version: "3"

services:
  node:
    build: .
    command: sh -c "yarn install && yarn start"
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ".:/home/node"
      - "/home/node/node_modules"
